In [40]:
import tsl
import torch
import numpy as np
import pandas as pd

print(f"tsl version  : {tsl.__version__}")
print(f"torch version: {torch.__version__}")

pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(edgeitems=3, precision=3)
torch.set_printoptions(edgeitems=2, precision=3)

# Utility functions ################
def print_matrix(matrix):
    return pd.DataFrame(matrix)

def print_model_size(model):
    tot = sum([p.numel() for p in model.parameters() if p.requires_grad])
    out = f"Number of model ({model.__class__.__name__}) parameters:{tot:10d}"
    print("=" * len(out))
    print(out)

tsl version  : 0.9.4
torch version: 2.3.1+cu121


In [41]:
from tsl.datasets import MetrLA

dataset = MetrLA(root='./data')

print(dataset)

MetrLA(length=34272, n_nodes=207, n_channels=1)


/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:96: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(datetime_idx[0],
/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')


In [42]:
print(f"Sampling period: {dataset.freq}")
print(f"Has missing values: {dataset.has_mask}")
print(f"Percentage of missing values: {(1 - dataset.mask.mean()) * 100:.2f}%")
print(f"Has exogenous variables: {dataset.has_covariates}")
print(f"Covariates: {', '.join(dataset.covariates.keys())}")

Sampling period: <5 * Minutes>
Has missing values: True
Percentage of missing values: 8.11%
Has exogenous variables: True
Covariates: dist


In [43]:
print_matrix(dataset.dist)

0        1        2       3       4       5       6        7    \
0       0.00      inf      inf     inf     inf     inf     inf      inf   
1        inf     0.00  2504.60 8563.80 8572.50 9561.00 9590.00  2506.30   
2        inf  1489.30     0.00 6971.30 6978.30 9148.20 9177.10  3995.70   
3        inf  6805.90  9293.60    0.00 1745.50 6068.80 5401.50  9312.30   
4        inf  6606.70  9111.30 1767.40    0.00 4464.00 3655.90  9113.10   
..       ...      ...      ...     ...     ...     ...     ...      ...   
202      inf      inf 10987.10     inf     inf     inf     inf 10133.60   
203      inf 10723.20  9461.80     inf     inf     inf     inf  8608.30   
204      inf      inf      inf     inf     inf     inf     inf      inf   
205  9599.80      inf      inf     inf     inf     inf     inf      inf   
206 10119.90  9374.80      inf 7922.00 6154.50     inf 9810.50      inf   

        8        9    ...     197     198      199  200     201     202  \
0       inf      inf  ...     inf     inf  3764.70  inf     inf 9204.30   
1       inf      inf  ...     inf     inf      inf  inf 4941.90 7559.20   
2       inf      inf  ...     inf 9467.80      inf  inf 6431.40 7821.80   
3       inf      inf  ...     inf 5906.50      inf  inf     inf     inf   
4       inf      inf  ...     inf 7207.10      inf  inf     inf     inf   
..      ...      ...  ...     ...     ...      ...  ...     ...     ...   
202     inf      inf  ...     inf     inf      inf  inf 9098.90    0.00   
203     inf      inf  ...     inf     inf      inf  inf 7283.50     inf   
204 9189.80  3171.10  ... 3672.40     inf      inf  inf     inf     inf   
205     inf 10167.50  ...     inf     inf 10500.80  inf     inf     inf   
206     inf      inf  ...     inf 2757.20      inf  inf     inf     inf   

        203  204     205      206  
0       inf  inf 8114.80 10009.70  
1   7877.20  inf     inf      inf  
2   9366.60  inf     inf  9837.00  
3       inf  inf     inf  7604.40  
4       inf  inf     inf  8905.00  
..      ...  ...     ...      ...  
202 4072.70  inf     inf      inf  
203    0.00  inf     inf      inf  
204     inf 0.00     inf      inf  
205     inf  inf    0.00      inf  
206     inf  inf 9018.70     0.00  

[207 rows x 207 columns]

In [44]:
dataset.dataframe()

nodes               773869 767541 767542 717447 717446 717445 773062 767620  \
channels                 0      0      0      0      0      0      0      0   
2012-03-01 00:00:00  64.38  67.62  67.12  61.50  66.88  68.75  65.12  67.12   
2012-03-01 00:05:00  62.67  68.56  65.44  62.44  64.44  68.11  65.00  65.00   
2012-03-01 00:10:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
2012-03-01 00:15:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
2012-03-01 00:20:00  64.00  63.75  60.00  59.00  66.50  66.25  64.50  64.25   
...                    ...    ...    ...    ...    ...    ...    ...    ...   
2012-06-27 23:35:00  65.00  65.89  68.56  61.67  32.83  54.56  62.44  63.33   
2012-06-27 23:40:00  61.38  65.62  66.50  62.75  32.83  50.50  62.00  67.00   
2012-06-27 23:45:00  67.00  59.67  69.56  61.00  32.83  44.78  64.22  63.78   
2012-06-27 23:50:00  66.75  62.25  66.00  59.62  32.83  53.00  64.29  64.12   
2012-06-27 23:55:00  65.11  66.89  66.78  61.22  32.83  49.56  65.78  65.11   

nodes               737529 717816  ... 772167 769372 774204 769806 717590  \
channels                 0      0  ...      0      0      0      0      0   
2012-03-01 00:00:00  59.62  62.75  ...  45.62  65.50  64.50  66.43  66.88   
2012-03-01 00:05:00  57.44  63.33  ...  50.67  69.88  66.67  58.56  62.00   
2012-03-01 00:10:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
2012-03-01 00:15:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
2012-03-01 00:20:00  63.88  65.38  ...  44.12  69.00  56.50  59.25  68.12   
...                    ...    ...  ...    ...    ...    ...    ...    ...   
2012-06-27 23:35:00  59.22  65.33  ...  52.89  69.00  65.11  55.67  66.33   
2012-06-27 23:40:00  65.25  67.12  ...  54.00  69.25  60.12  60.50  67.25   
2012-06-27 23:45:00  59.78  57.67  ...  51.33  67.89  64.33  57.00  66.00   
2012-06-27 23:50:00  60.88  66.25  ...  51.12  69.38  61.62  60.50  65.62   
2012-06-27 23:55:00  63.00  61.67  ...  56.00  67.44  64.89  60.89  64.22   

nodes               717592 717595 772168 718141 769373  
channels                 0      0      0      0      0  
2012-03-01 00:00:00  59.38  69.00  59.25  69.00  61.88  
2012-03-01 00:05:00  61.11  64.44  55.89  68.44  62.88  
2012-03-01 00:10:00  62.50  65.62  61.38  69.86  62.00  
2012-03-01 00:15:00  62.50  65.62  61.38  69.86  62.00  
2012-03-01 00:20:00  62.50  65.62  61.38  69.86  62.00  
...                    ...    ...    ...    ...    ...  
2012-06-27 23:35:00  62.44  66.78  64.89  69.67  62.33  
2012-06-27 23:40:00  59.38  66.00  61.25  69.00  62.00  
2012-06-27 23:45:00  62.67  68.67  63.33  67.44  61.22  
2012-06-27 23:50:00  66.38  69.50  63.00  67.88  63.50  
2012-06-27 23:55:00  66.44  68.44  63.56  68.67  61.78  

[34272 rows x 207 columns]

In [45]:
print(f"Default similarity: {dataset.similarity_score}")
print(f"Available similarity options: {dataset.similarity_options}")
print("==========================================")

sim = dataset.get_similarity("distance")  # or dataset.compute_similarity()

print("Similarity matrix W:")
print_matrix(sim)

Default similarity: distance
Available similarity options: {'distance'}
Similarity matrix W:


0    1    2    3    4    5    6    7    8    9    ...  197  198  199  \
0   1.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.12   
1   0.00 1.00 0.39 0.00 0.00 0.00 0.00 0.39 0.00 0.00  ... 0.00 0.00 0.00   
2   0.00 0.72 1.00 0.00 0.00 0.00 0.00 0.09 0.00 0.00  ... 0.00 0.00 0.00   
3   0.00 0.00 0.00 1.00 0.63 0.00 0.01 0.00 0.00 0.00  ... 0.00 0.01 0.00   
4   0.00 0.00 0.00 0.63 1.00 0.05 0.14 0.00 0.00 0.00  ... 0.00 0.00 0.00   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.22  ... 0.13 0.00 0.00   
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.32 0.00   

     200  201  202  203  204  205  206  
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
1   0.00 0.03 0.00 0.00 0.00 0.00 0.00  
2   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
3   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
4   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
..   ...  ...  ...  ...  ...  ...  ...  
202 0.00 0.00 1.00 0.08 0.00 0.00 0.00  
203 0.00 0.00 0.00 1.00 0.00 0.00 0.00  
204 0.00 0.00 0.00 0.00 1.00 0.00 0.00  
205 0.00 0.00 0.00 0.00 0.00 1.00 0.00  
206 0.00 0.00 0.00 0.00 0.00 0.00 1.00  

[207 rows x 207 columns]

In [46]:
connectivity = dataset.get_connectivity(threshold=0.1,
                                        include_self=False,
                                        normalize_axis=1,
                                        layout="edge_index")

In [47]:
edge_index, edge_weight = connectivity

print(f'edge_index {edge_index.shape}:\n', edge_index)
print(f'edge_weight {edge_weight.shape}:\n', edge_weight)

edge_index (2, 1515):
 [[  0   0   0 ... 206 206 206]
 [ 13  36  58 ... 157 162 198]]
edge_weight (1515,):
 [0.08  0.163 0.031 ... 0.045 0.031 0.115]


In [48]:
from tsl.ops.connectivity import edge_index_to_adj

adj = edge_index_to_adj(edge_index, edge_weight)
print(f'A {adj.shape}:')
print_matrix(adj)

A (207, 207):


0    1    2    3    4    5    6    7    8    9    ...  197  198  199  \
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.03   
1   0.00 0.00 0.14 0.00 0.00 0.00 0.00 0.14 0.00 0.00  ... 0.00 0.00 0.00   
2   0.00 0.19 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
3   0.00 0.00 0.00 0.00 0.12 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
4   0.00 0.00 0.00 0.11 0.00 0.00 0.02 0.00 0.00 0.00  ... 0.00 0.00 0.00   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.09  ... 0.05 0.00 0.00   
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.00 0.00   
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00  ... 0.00 0.05 0.00   

     200  201  202  203  204  205  206  
0   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
1   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
2   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
3   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
4   0.00 0.00 0.00 0.00 0.00 0.00 0.00  
..   ...  ...  ...  ...  ...  ...  ...  
202 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
203 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
204 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
205 0.00 0.00 0.00 0.00 0.00 0.00 0.00  
206 0.00 0.00 0.00 0.00 0.00 0.00 0.00  

[207 rows x 207 columns]

In [49]:
print(f'Sparse edge weights:\n', adj[edge_index[1], edge_index[0]])


Sparse edge weights:
 [0.08  0.163 0.031 ... 0.045 0.031 0.115]


In [50]:
import torch.nn as nn

from tsl.nn.blocks.encoders import RNN
from tsl.nn.layers import NodeEmbedding, DiffConv
from einops.layers.torch import Rearrange  # reshape data with Einstein notation


class TimeThenSpaceModel(nn.Module):
    def __init__(self, input_size: int, n_nodes: int, horizon: int,
                 hidden_size: int = 32,
                 rnn_layers: int = 1,
                 gnn_kernel: int = 2):
        super(TimeThenSpaceModel, self).__init__()

        self.encoder = nn.Linear(input_size, hidden_size)

        self.node_embeddings = NodeEmbedding(n_nodes, hidden_size)

        self.time_nn = RNN(input_size=hidden_size,
                           hidden_size=hidden_size,
                           n_layers=rnn_layers,
                           cell='gru',
                           return_only_last_state=True)
        
        self.space_nn = DiffConv(in_channels=hidden_size,
                                 out_channels=hidden_size,
                                 k=gnn_kernel)

        self.decoder = nn.Linear(hidden_size, input_size * horizon)
        self.rearrange = Rearrange('b n (t f) -> b t n f', t=horizon)

    def forward(self, x, edge_index, edge_weight):
        # x: [batch time nodes features]
        x_enc = self.encoder(x)  # linear encoder: x_enc = xΘ + b
        x_emb = x_enc + self.node_embeddings()  # add node-identifier embeddings
        h = self.time_nn(x_emb)  # temporal processing: x=[b t n f] -> h=[b n f]
        z = self.space_nn(h, edge_index, edge_weight)  # spatial processing
        x_out = self.decoder(z)  # linear decoder: z=[b n f] -> x_out=[b n t⋅f]
        x_horizon = self.rearrange(x_out)
        return x_horizon

In [ ]:
from tsl.metrics.torch import MaskedMAE, MaskedMAPE
from tsl.engines import Predictor

loss_fn = MaskedMAE()

metrics = {'mae': MaskedMAE(),
           'mape': MaskedMAPE(),
           'mae_at_15': MaskedMAE(at=2),  # '2' indicates the third time step,
                                          # which correspond to 15 minutes ahead
           'mae_at_30': MaskedMAE(at=5),
           'mae_at_60': MaskedMAE(at=11)}

# setup predictor
predictor = Predictor(
    model=stgnn,                   # our initialized model
    optim_class=torch.optim.Adam,  # specify optimizer to be used...
    optim_kwargs={'lr': 0.001},    # ...and parameters for its initialization
    loss_fn=loss_fn,               # which loss function to be used
    metrics=metrics                # metrics to be logged during train/val/test
)

NameError: name 'stgnn' is not defined

In [23]:
from tsl.datasets import AirQuality, MetrLA, PemsBay
from tsl.ops.imputation import add_missing_values
from tsl.data import ImputationDataset, SpatioTemporalDataModule
from tsl.data.preprocessing import StandardScaler
from tsl.transforms import MaskInput

dataset = MetrLA()

/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:96: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(datetime_idx[0],
/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')


In [27]:
dataset = add_missing_values(MetrLA(),
                                  p_fault=0.0015,
                                  p_noise=0.05,
                                  min_seq=12,
                                  max_seq=12 * 4,
                                  seed=9101112)

# encode time of the day and use it as exogenous variable
covariates = {'u': dataset.datetime_encoded('day').values}

# get adjacency matrix
adj = dataset.get_connectivity(**{'method': 'distance',
'threshold': 0.1,
'include_self': False,
'layout': 'edge_index'
})

# instantiate dataset
torch_dataset = ImputationDataset(target=dataset.dataframe(),
                                    mask=dataset.training_mask,
                                    eval_mask=dataset.eval_mask,
                                    covariates=covariates,
                                    transform=MaskInput(),
                                    connectivity=adj,
                                    window=24,
                                    stride=1)

scalers = {'target': StandardScaler(axis=(0, 1))}

dm = SpatioTemporalDataModule(
    dataset=torch_dataset,
    scalers=scalers,
    splitter=dataset.get_splitter(**{'val_len': 0.1, 'test_len': 0.2}),
    batch_size=32,
    workers=0)
dm.setup(stage='fit')
dm.trainset = list(range(len(torch_dataset)))


/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:96: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  date_range = pd.date_range(datetime_idx[0],
/data/p.magos/.pyenv/versions/3.11.9/lib/python3.11/site-packages/tsl/datasets/metr_la.py:109: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df = df.replace(to_replace=0., method='ffill')


In [35]:
dm.teardown(stage='fit')
dm

SpatioTemporalDataModule(train_len=34249, val_len=2716, test_len=6849, scalers=[target], batch_size=32)