In [115]:
import torch.nn.functional as F
import torch
from GRGN.Utils.reshapes import reshape_to_original

In [116]:
out = torch.rand(1, 2, 6)
out[0][1][-2:] = out[0][0][-2:]
out1 = torch.tensor(out)


/var/folders/2f/0xjdq0xn6b3cfw3v2k2svn3m0000gn/T/ipykernel_58384/4026433915.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  out1 = torch.tensor(out)


In [117]:
out

tensor([[[0.8681, 0.3033, 0.7846, 0.0203, 0.1975, 0.6623],
         [0.6018, 0.1305, 0.4733, 0.6715, 0.1975, 0.6623]]])

In [118]:
out1

tensor([[[0.8681, 0.3033, 0.7846, 0.0203, 0.1975, 0.6623],
         [0.6018, 0.1305, 0.4733, 0.6715, 0.1975, 0.6623]]])

In [119]:
out = reshape_to_original(out, 2, 1, 2)
out

tensor([[0.8681, 0.3033, 0.6018, 0.1305, 0.7846, 0.0203, 0.4733, 0.6715, 0.1975,
         0.6623, 0.1975, 0.6623]])

In [120]:
out1[..., -2:] = F.softmax(out1[..., -2:], dim=-1)
out1[..., -2:]

tensor([[[0.3859, 0.6141],
         [0.3859, 0.6141]]])

In [121]:
out[..., -2*2:-2*2 + 2] = F.softmax(out[..., -2*2:-2*2 + 2], dim=-1)
out[..., -2*2:-2*2 + 2]

tensor([[0.3859, 0.6141]])